---
abstract: 'Control how many instances of an application run in parallel, using DBI as the IPC method.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  DBD::SQLite: 0
  DBI: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Concurrency-DBI
no_index:
  file:
    - t/LocalTest.pm
provides:
  IPC::Concurrency::DBI:
    file: lib/IPC/Concurrency/DBI.pm
    version: v1.0.3
  IPC::Concurrency::DBI::Application:
    file: lib/IPC/Concurrency/DBI/Application.pm
    version: v1.0.3
  IPC::Concurrency::DBI::Application::Instance:
    file: lib/IPC/Concurrency/DBI/Application/Instance.pm
    version: v1.0.3
requires:
  Carp: 0
  Data::Dumper: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=ipc-concurrency-dbi
  homepage: https://metacpan.org/release/IPC-Concurrency-DBI
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/IPC-Concurrency-DBI
version: v1.0.3
